### ISSUE TITLE
Typo on arcane anthology spells

### ISSUE THREAD

**Issue by pcd1193182** [PCGen/pcgen-newsources#266]
Tears to Wine has "liquit" in the "Target" field.

**Comment by LegacyKing** [comment]
Thanks for the notification, but I tend to have a policy of not acting on issues for in-progress data sets. New Source is meant for books that are in various states of readiness, and to act upon reports such as these would set a precedent I would rather avoid. I will gladly accept any updates to the files themselves, but please do not expect me to correct problems inside of these sets.

Cheers,
